server:
  port: 3344
spring:
  application:
    name: config-server-3344
  cloud:
    config:
      server:
        git:
          uri: git@github.com:mjay9jojo/cloud-config-server.git
          search-paths:
            - cloud-config-server
          default-label: master
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka


